version: 2.11.1.{build}
branches:
    only:
        - master
skip_tags: true
clone_folder: C:\Cube\Cube.Pdf
image: Visual Studio 2017
nuget:
    project_feed: true
    disable_publish_on_pr: true
platform: Any CPU
configuration: Release
before_build:
    - ps: Start-FileDownload https://www.cube-soft.jp/archive/gs-x64.7z
    - 7z x -o"..\native\x64" gs-x64.7z
    - nuget sources add -name Cube.Core -source https://ci.appveyor.com/nuget/cube.core
    - nuget sources add -name Cube.FileSystem -source https://ci.appveyor.com/nuget/cube.filesystem
    - nuget sources add -name Cube.Images -source https://ci.appveyor.com/nuget/cube.images
    - nuget sources add -name Cube.Forms -source https://ci.appveyor.com/nuget/cube.forms
    - nuget sources add -name Cube.Xui -source https://ci.appveyor.com/nuget/cube.xui
    - nuget restore Cube.Pdf.Applications.sln
build:
    parallel: true
    project: Cube.Pdf.Applications.sln
    publish_nuget: true
    verbosity: minimal
after_build:
    - xcopy /q /Y /I Applications\Converter\Forms\bin\Release CubePdf
    - xcopy /q /Y /I Applications\Converter\Proxy\bin\Release CubePdf.Proxy
    - xcopy /q /Y /I Applications\Editor\Forms\bin\Release CubePdf.Utility
    - xcopy /q /Y /I Applications\Editor\Proxy\bin\Release CubePdf.Utility.Proxy
    - xcopy /q /Y /I ..\native\x64\bin\gsdll32.dll Tests\bin\Release
    - xcopy /q /Y /I ..\native\x64\lib\*.* Tests\bin\Release\lib
    - xcopy /q /Y /I ..\native\x64\bin\gsdll32.dll Applications\Converter\Tests\bin\Release
    - xcopy /q /Y /I ..\native\x64\lib\*.* Applications\Converter\Tests\bin\Release\lib
    - xcopy /q /Y /I ..\packages\PdfiumViewer.Native.x86_64.no_v8-no_xfa.2018.4.8.256\Build\x64\pdfium.dll Tests\bin\Release
    - xcopy /q /Y /I ..\packages\PdfiumViewer.Native.x86_64.no_v8-no_xfa.2018.4.8.256\Build\x64\pdfium.dll Applications\Editor\Tests\bin\Release
artifacts:
    - path: CubePdf
    - path: CubePdf.Proxy
    - path: CubePdf.Utility
    - path: CubePdf.Utility.Proxy
    - path: CoverResults.xml
test_script:
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.Pdf.Tests.dll
      -targetdir:Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -output:CoverResults.xml
      -filter:"+[Cube]* -[Cube]*NativeMethods -[Cube]*Properties.*"
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:Cube.Pdf.Tests.Converter.dll
      -targetdir:Applications\Converter\Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:CoverResults.xml
      -filter:"+[Cube]* -[Cube]*NativeMethods -[Cube]*Properties.* -[Cube]*Form -[Cube]*.Program"
    - >
      ..\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe
      -log:Error
      -register:user
      -target:nunit3-console.exe
      -targetargs:"Cube.Pdf.Tests.Editor.dll --process=Single --agents=1 --workers=1 --timeout=10000"
      -targetdir:Applications\Editor\Tests\bin\Release
      -returntargetcode
      -hideskipped:All
      -mergeoutput
      -output:CoverResults.xml
      -filter:"+[Cube]* -[Cube]*NativeMethods -[Cube]*Properties.* -[Cube]*Window -[Cube]*Control -[Cube]*.App"
after_test:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "CoverResults.xml"